name: Pull Request

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  install-check-tests:
    name: Install, Type Check, Test, and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Check types
        run: pnpm tsc
      - name: Test
        run: pnpm t
      - name: Lint
        run: pnpm lint


